FileVersion = 1

[Project]
Name = "xxHash-beef"
DefaultNamespace = "xxHash"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\xxHash.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\xxHash.lib"]